#!/usr/bin/env python3
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]

def t(rel): return (ROOT/rel).read_text()
def req(cond,msg):
    if not cond: raise AssertionError(msg)

def main():
    hs=t('cores/lgt8f/HardwareSerial.cpp')
    req('if (baud == 0) return;' in hs,'HardwareSerial zero-baud guard missing')
    req('uint64_t denom' in hs and '4095u' in hs,'HardwareSerial range arithmetic hardening missing')
    tone=t('cores/lgt8f/Tone.cpp')
    req('frequency == 0' in tone,'tone zero-frequency guard missing')
    req('2ULL * (uint64_t)frequency' in tone,'tone duration overflow guard missing')
    pulse=t('cores/lgt8f/wiring_pulse.c')
    req(pulse.count('pin >= NUM_PIN_TABLE_ENTRIES')>=2,'pulseIn invalid-pin guards missing')
    req('uint64_t clocks' in pulse and 'uint64_t cycles' in pulse,'pulseIn overflow hardening missing')
    wi=t('cores/lgt8f/WInterrupts.c')
    req('userFunc == 0 || mode < 0 || mode > 3' in wi,'attachInterrupt input guard missing')
    ss=t('libraries/SoftwareSerial/SoftwareSerial.cpp')
    req('speed <= 0' in ss,'SoftwareSerial zero/negative speed guard missing')
    req('_transmitPortRegister == NULL' in ss and '_pcint_maskreg == NULL' in ss,'SoftwareSerial invalid-pin guard missing')
    wire=t('libraries/Wire/Wire.cpp')
    req('if (endTransmission(false) != 0)' in wire,'Wire internal-address preamble failure guard missing')
    twi=t('libraries/Wire/utility/twi.c')
    req('previous_TWAMR' in twi,'TWI timeout recovery must preserve TWAMR')
    req('twi_txBufferIndex >= twi_txBufferLength' in twi,'TWI slave TX bounds guard missing')
    common=t('libraries/LGT8Unlocked/src/lgt/common.h')
    req('PMX1 = (uint8_t)(value & 0x07u)' in common,'PMX1 reserved-bit mask missing')
    req('PMX2 = (uint8_t)(value & 0x67u)' in common,'PMX2 reserved-bit mask missing')
    adc=t('libraries/LGT8Unlocked/src/lgt/adc.h')
    req('adcUpdate' in adc and 'adcClearFlag' in adc,'ADC W1C helpers missing')
    req('consecutive==0u' in adc,'ADC monitor zero-consecutive reject missing')
    req('(ADCSRA&(_BV(ADSC)|_BV(ADIF)))' in adc,'ADC calibration busy/pending guard missing')
    comp=t('libraries/LGT8Unlocked/src/lgt/comparator.h')
    req('c0Write' in comp and '~_BV(C0I)' in comp and 'c1Write' in comp and '~_BV(C1I)' in comp,'Comparator W1C-safe writes missing')
    ud=t('libraries/LGT8Unlocked/src/lgt/udsc.h')
    req('"ld r0,Z"' in ud and 'getX()' in ud,'uDSC load16 must use documented R0->DX pair semantics')
    req('setX(v)' in ud and '"st Z,r0"' in ud,'uDSC store16 must use documented DX->R0 semantics')
    us=t('libraries/LGT8Unlocked/src/lgt/usart.h')
    req('UCSR0A&0x03u' in us,'USART MPCM W1C-safe mask missing')
    req('DDRD&=(uint8_t)~_BV(DDD4)' in us,'USART-SPI end must release XCK')
    sy=t('libraries/LGT8Unlocked/src/lgt/system.h')
    req('if((uint8_t)src>3u)return InvalidArgument' in sy,'Clock source enum guard missing')
    req('v!=4u' in sy,'Power peripheral enum guard missing')
    req('mode==4u||mode==5u||mode>7u' in sy,'Sleep reserved-mode guard missing')
    req('MCUSR=swd' in sy,'Reset-cause clear must preserve SWD state')
    gpio=t('libraries/LGT8Unlocked/src/lgt/gpio.h')
    req('*mask==0u' in gpio,'PCINT group cleanup missing')
    timer=t('libraries/LGT8Unlocked/src/lgt/timer.h')
    req('oc0aTicks>15u||oc0bTicks>15u' in timer,'Timer0 deadtime range guard missing')
    req('volatile uint8_t *p=(volatile uint8_t*)&ICR1' in timer,'Timer1 high-speed capture split-read missing')
    fl=t('libraries/LGT8Unlocked/src/lgt/flash_iap.h')
    req('if(!(PMCR&_BV(RCMEN))) return NotReady;' in fl,'Flash IAP must fail closed when HFRC off')
    req('if(PRR1&_BV(PREFL)) return NotReady;' in fl,'Flash IAP must reject gated controller')
    wdt=t('libraries/WDT/WDT.h')
    # final write must happen before restoring SREG
    a=wdt.find('sts    %[wdtcsr], %[wdce_wde]')
    b=wdt.find('sts    %[wdtcsr], %[wdie_val]',a)
    c=wdt.find('out    __SREG__,__tmp_reg__',a)
    req(a>=0 and b>a and c>b,'WDT unlock window can be interrupted')
    safe=t('libraries/LGT8Unlocked/src/lgt/safety.h')
    platform=t('platform.txt')
    req('#define LGT8_UNLOCKED_RECOVERY_SAFE 1' in safe,'recovery-safe default missing')
    req('LGT8_UNLOCKED_ALLOW_HIGH_DRIVE=1' in platform,'HDR must stay enabled for this test build')
    print('PASS RC2 hardening regression: 27 bug classes/interlocks')
if __name__=='__main__': main()
